#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

sudo apt update
sudo apt install -y stow
sudo chsh -s /bin/zsh coder

rm -f ~/.bashrc ~/.gitconfig
stow -d $(dirname "$SCRIPT_DIR") -t ~/ .
